/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package House_creator;

import java.util.Random;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.event.ListDataEvent;
import javax.swing.event.ListDataListener;

/**
 *
 * @author hass-pc
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public final DefaultListModel<String> Habitaciones, Eventos, Sensores;
    public final DefaultComboBoxModel<String> combomodel;
    public Redactor red;
    public Lector lec;
    public Main() {
        initComponents();
        Habitaciones = new DefaultListModel<>();
        Eventos = new DefaultListModel<>();
        Sensores = new DefaultListModel<>();
        combomodel = new DefaultComboBoxModel<>();
        ListaCuartos.setModel(Habitaciones);
        ListaSensores.setModel(Sensores);
        ListaEventos.setModel(Eventos);
        Habitaciones.addListDataListener(new ListDataListener() {

            @Override
            public void intervalAdded(ListDataEvent e) {
                String text = Habitaciones.elementAt(e.getIndex0()).split(";")[0];
                combomodel.addElement(text);
            }

            @Override
            public void intervalRemoved(ListDataEvent e) {
                String text = Habitaciones.elementAt(e.getIndex0()).split(";")[0];
                combomodel.removeElement(text);
            }

            @Override
            public void contentsChanged(ListDataEvent e) {
                combomodel.removeAllElements();
                for (int i = 0; i < Habitaciones.getSize(); i++) {
                    String text = Habitaciones.elementAt(i).split(";")[0];
                    combomodel.addElement(text);
                }
            }
        });
        sensorubicacion.setModel(combomodel);
        red = new Redactor(this);
        lec = new Lector(this);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        NombreCasa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaCuartos = new javax.swing.JList();
        agregarcuarto = new javax.swing.JButton();
        borrarcuarto = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jlabelxx = new javax.swing.JLabel();
        sensorid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        sensortipo = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        sensorubicacion = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        sensorano = new javax.swing.JTextField();
        sensormes = new javax.swing.JTextField();
        sensordia = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        eventostiposensor = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        eventonombre = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaSensores = new javax.swing.JList();
        agregarsensor = new javax.swing.JButton();
        borrarsensor = new javax.swing.JButton();
        eventovalorexceeded = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        eventounidadmedida = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        ListaEventos = new javax.swing.JList();
        agregarevento = new javax.swing.JButton();
        borrarevento = new javax.swing.JButton();
        guardar = new javax.swing.JButton();
        cargar = new javax.swing.JButton();
        daterandom = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre de la Casa");

        jLabel2.setText("Habitaciones");

        jScrollPane1.setMaximumSize(new java.awt.Dimension(258, 130));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(258, 130));

        ListaCuartos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(ListaCuartos);

        agregarcuarto.setText("Add Room");
        agregarcuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarcuartoActionPerformed(evt);
            }
        });

        borrarcuarto.setText("Delete Room");
        borrarcuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarcuartoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Sensores");

        jlabelxx.setText("Id");

        jLabel5.setText("Tipo de Sensor");

        sensortipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sensor Medidor De Flujo De Agua", "Sensor de Movimiento Inalámbrico", "Sensor de Puerta Inalámbrica", "Sensor de Gas", "Sensor de Humo", "Sensor de Temperatura y Humedad", "Perchero Gancho con Camara Espia Oculta y Sensor Sonido", "Sensor Detector De Lluvia", "Sensor de Presencia (PIR)", "Sensor de Inundacion", "Sensores de luminosidad", " " }));

        jLabel6.setText("Ubicacion");

        sensorubicacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setText("Fecha de Instalacion");

        jLabel8.setText("Año");

        jLabel9.setText("Mes");

        jLabel10.setText("Dia");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Eventos");

        jLabel12.setText("Tipo de Sensor");

        eventostiposensor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sensor Medidor De Flujo De Agua", "Sensor de Movimiento Inalámbrico", "Sensor de Puerta Inalámbrica", "Sensor de Gas", "Sensor de Humo", "Sensor de Temperatura y Humedad", "Perchero Gancho con Camara Espia Oculta y Sensor Sonido", "Sensor Detector De Lluvia", "Sensor de Presencia (PIR)", "Sensor de Inundacion", "Sensores de luminosidad", " " }));

        jLabel13.setText("Nombre del Evento");

        jLabel14.setText("Valor Sobrepasado");

        ListaSensores.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(ListaSensores);

        agregarsensor.setText("Agregar");
        agregarsensor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarsensorActionPerformed(evt);
            }
        });

        borrarsensor.setText("Eliminar");
        borrarsensor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarsensorActionPerformed(evt);
            }
        });

        jLabel15.setText("Unidad de Medida");

        ListaEventos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(ListaEventos);

        agregarevento.setText("Agregar");
        agregarevento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregareventoActionPerformed(evt);
            }
        });

        borrarevento.setText("Eliminar");
        borrarevento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrareventoActionPerformed(evt);
            }
        });

        guardar.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        cargar.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        cargar.setText("Cargar");
        cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarActionPerformed(evt);
            }
        });

        daterandom.setText("Aleatorio");
        daterandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daterandomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(agregarcuarto)
                                .addGap(6, 6, 6)
                                .addComponent(borrarcuarto))
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(eventonombre, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eventovalorexceeded, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eventounidadmedida, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(eventostiposensor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(agregarevento)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(4, 4, 4)
                                .addComponent(NombreCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(150, 150, 150)
                                .addComponent(jLabel11))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlabelxx)
                                        .addGap(18, 18, 18)
                                        .addComponent(sensorid, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel6)
                                        .addGap(10, 10, 10)
                                        .addComponent(sensorubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sensortipo, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel8)
                                        .addGap(43, 43, 43)
                                        .addComponent(jLabel9)
                                        .addGap(23, 23, 23)
                                        .addComponent(jLabel10))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(109, 109, 109)
                                        .addComponent(sensorano, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(sensormes, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(sensordia, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(daterandom))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(agregarsensor)
                                        .addGap(6, 6, 6)
                                        .addComponent(borrarsensor)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(189, 189, 189)
                                        .addComponent(borrarevento))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cargar, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 18, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1)
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel11)))
                    .addComponent(NombreCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(agregarcuarto)
                            .addComponent(borrarcuarto)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(eventostiposensor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(eventonombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sensorid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sensorubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlabelxx)
                                    .addComponent(jLabel6))))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel5))
                            .addComponent(sensortipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sensorano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sensormes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(sensordia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(daterandom)))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(agregarsensor)
                            .addComponent(borrarsensor)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(eventovalorexceeded, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(eventounidadmedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(borrarevento)
                            .addComponent(agregarevento))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cargar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarcuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarcuartoActionPerformed
        // TODO add your handling code here:
        RoomCreator cr = new  RoomCreator(this, true);
        cr.setVisible(true);
        if (!cr.generate.equals("")) {
            Habitaciones.addElement(cr.generate);
        }
    }//GEN-LAST:event_agregarcuartoActionPerformed

    private void borrarcuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarcuartoActionPerformed
        // TODO add your handling code here:
        if (ListaCuartos.getSelectedIndex()!=-1)
            Habitaciones.remove(ListaCuartos.getSelectedIndex());
    }//GEN-LAST:event_borrarcuartoActionPerformed

    private void agregarsensorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarsensorActionPerformed
        // TODO add your handling code here:
        String fecha = sensorano.getText()+"-"+sensormes.getText()+"-"+sensordia.getText();
        String data = sensorid.getText()+";"+sensorubicacion.getSelectedItem().toString()+";";
        data+=sensortipo.getSelectedItem().toString()+";"+fecha;
        Sensores.addElement(data);
        String tt = sensorid.getText();
        try {
            sensorid.setText((Integer.parseInt(tt)+1)+"");
        } catch (Exception ex) {
            
        }
    }//GEN-LAST:event_agregarsensorActionPerformed

    private void borrarsensorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarsensorActionPerformed
        // TODO add your handling code here:
        if (ListaSensores.getSelectedIndex()!=-1)
            Sensores.remove(ListaSensores.getSelectedIndex());
    }//GEN-LAST:event_borrarsensorActionPerformed

    private void agregareventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregareventoActionPerformed
        // TODO add your handling code here:
        String data = eventonombre.getText()+";"+eventostiposensor.getSelectedItem().toString()+";";
        data+= eventovalorexceeded.getText()+";"+eventounidadmedida.getText();
        Eventos.addElement(data);
    }//GEN-LAST:event_agregareventoActionPerformed

    private void borrareventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrareventoActionPerformed
        // TODO add your handling code here:
        if (ListaEventos.getSelectedIndex()!=-1)
            Eventos.remove(ListaEventos.getSelectedIndex());
    }//GEN-LAST:event_borrareventoActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        // TODO add your handling code here:
        red.Asignar();
    }//GEN-LAST:event_guardarActionPerformed

    private void cargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarActionPerformed
        // TODO add your handling code here:
        lec.Leer();
    }//GEN-LAST:event_cargarActionPerformed

    private void daterandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daterandomActionPerformed
        // TODO add your handling code here:
        Random r = new Random();
        int randomNum = r.nextInt((2015 - 1998) + 1) + 1998;
        sensorano.setText(randomNum+"");
        randomNum = r.nextInt(12) + 1;
        sensormes.setText(randomNum+"");
        randomNum = r.nextInt(28) + 1;
        sensordia.setText(randomNum+"");
    }//GEN-LAST:event_daterandomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList ListaCuartos;
    private javax.swing.JList ListaEventos;
    private javax.swing.JList ListaSensores;
    public javax.swing.JTextField NombreCasa;
    private javax.swing.JButton agregarcuarto;
    private javax.swing.JButton agregarevento;
    private javax.swing.JButton agregarsensor;
    private javax.swing.JButton borrarcuarto;
    private javax.swing.JButton borrarevento;
    private javax.swing.JButton borrarsensor;
    private javax.swing.JButton cargar;
    private javax.swing.JButton daterandom;
    private javax.swing.JTextField eventonombre;
    private javax.swing.JComboBox eventostiposensor;
    private javax.swing.JTextField eventounidadmedida;
    private javax.swing.JTextField eventovalorexceeded;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel jlabelxx;
    private javax.swing.JTextField sensorano;
    private javax.swing.JTextField sensordia;
    private javax.swing.JTextField sensorid;
    private javax.swing.JTextField sensormes;
    private javax.swing.JComboBox sensortipo;
    private javax.swing.JComboBox sensorubicacion;
    // End of variables declaration//GEN-END:variables
}
